src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
#[ORM\HasLifecycleCallbacks]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column]
    private bool $isVerified = false;

    #[ORM\Column(length: 100)]
    private ?string $user_type = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    /**
     * @var Collection<int, Job>
     */
    #[ORM\OneToMany(targetEntity: Job::class, mappedBy: 'recruiter')]
    private Collection $jobs;

    /**
     * @var Collection<int, Application>
     */
    #[ORM\OneToMany(targetEntity: Application::class, mappedBy: 'jobseeker')]
    private Collection $applications;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $company = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $skills = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $profilePic = null;

    public function __construct()
    {
        $this->jobs = new ArrayCollection();
        $this->applications = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    public function addRole(string $role): self
    {
        if (!in_array($role, $this->roles)) {
            $this->roles[] = $role;
        }

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getUserType(): ?string
    {
        return $this->user_type;
    }

    public function setUserType(string $user_type): static
    {
        $this->user_type = $user_type;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    /**
     * @return Collection<int, Job>
     */
    public function getJobs(): Collection
    {
        return $this->jobs;
    }

    public function addJob(Job $job): static
    {
        if (!$this->jobs->contains($job)) {
            $this->jobs->add($job);
            $job->setRecruiter($this);
        }

        return $this;
    }

    public function removeJob(Job $job): static
    {
        if ($this->jobs->removeElement($job)) {
            // set the owning side to null (unless already changed)
            if ($job->getRecruiter() === $this) {
                $job->setRecruiter(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Application>
     */
    public function getApplications(): Collection
    {
        return $this->applications;
    }

    public function addApplication(Application $application): static
    {
        if (!$this->applications->contains($application)) {
            $this->applications->add($application);
            $application->setJobseeker($this);
        }

        return $this;
    }

    public function removeApplication(Application $application): static
    {
        if ($this->applications->removeElement($application)) {
            // set the owning side to null (unless already changed)
            if ($application->getJobseeker() === $this) {
                $application->setJobseeker(null);
            }
        }

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(?string $company): static
    {
        $this->company = $company;

        return $this;
    }

    public function getSkills(): ?string
    {
        return $this->skills;
    }

    public function setSkills(?string $skills): static
    {
        $this->skills = $skills;

        return $this;
    }

    #[ORM\PrePersist]
    public function setCreatedAt(): void
    {
        if ($this->createdAt === null) {
            $this->createdAt = new \DateTimeImmutable();
        }
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getProfilePic(): ?string
    {
        return $this->profilePic ?: 'anonymous.jpg';
    }

    public function setProfilePic(?string $profilePic): static
    {
        $this->profilePic = $profilePic;

        return $this;
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use AllowDynamicProperties;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;
use App\Form\editProfileType;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\String\Slugger\SluggerInterface;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

#[AllowDynamicProperties] class ProfileController extends AbstractController
{
    private $security;

    public function __construct(Security $security,ParameterBagInterface $parameters)
    {
        $this->security = $security;
        $this->parameters = $parameters;
    }
    #[Route('/profile', name: 'app_profile')]
    public function index(): Response
    {
        return $this->render('profile/index.html.twig', [
            'controller_name' => 'ProfileController',
        ]);
    }

    #[Route('/editProfile', name: 'app_editProfile')]
    public function edit(Request $request,SluggerInterface $slugger,EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();
        $form = $this->createForm(editProfileType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $user->setName($form->get('name')->getData());
            $user->setLastName($form->get('last_name')->getData());
            $user->setEmail($form->get('email')->getData());
            if ($this->security->isGranted('ROLE_JOBSEEKER')) {
                $user->setSkills($form->get('skills')->getData());
            }
            if ($this->security->isGranted('ROLE_RECRUITER')) {
                $user->setCompany($form->get('company')->getData());
            }

            $picture = $form->get('profilePic')->getData();

            if ($picture) {
                $originalFilename = pathinfo($picture->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$picture->guessExtension();

                $picturesDirectory = $this->getParameter('pictures_directory');

                try {
                    $picture->move($picturesDirectory, $newFilename);
                } catch (FileException $e) {
                    // Handle exception if something happens during file upload
                }
                $user->setProfilePic($newFilename);
            }
            $entityManager->persist($user);
            $entityManager->flush();
        }

        return $this->render('profile/editProfile.html.twig', [
            'form' => $form,
        ]);
    }
}

templates/profile/editProfile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit your profile{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset("css/formStyles.css") }}"
{% endblock %}

{% block header %}
{% endblock %}

{% block main %}

    <div class="container">
        {#  <img src="{{ asset('images/register.webp') }}" alt="Registration Image" class="registration-image"> #}
        <div class="formulaire">

            <h1>Edit Your Profile</h1>

            {{ form_errors(form) }}

            {{ form_start(form) }}

            {{ form_row(form.name) }}
            {{ form_row(form.last_name) }}

            {{ form_row(form.email) }}
            {{ form_row(form.skills) }}

            {{ form_row(form.profilePic) }}

            <button type="submit" class="btn">Save</button>
            {{ form_end(form) }}

        </div>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Your Profile{% endblock %}

{% block main %}
    <div class="container w-75 p-3 d-flex justify-content-center  " >
        <div class="card p-4">
            <div class=" image d-flex flex-column justify-content-center align-items-center">
                <button class="btn btn-secondary">
                    <img src="{{ asset('uploads/profilePictures/' ~ app.user.profilePic) }}" alt="Profile Picture" height="150" width="150" />
                </button> <span class="name mt-3 h2">{{ app.user.name }} {{ app.user.lastName }}</span > <span  class="h3">{{ app.user.email }}</span>
                {#  <div class="d-flex flex-row justify-content-center align-items-center gap-2">
                    <span class="idd1">Oxc4c16a645_b21a</span>
                    <span><i class="fa fa-copy"></i></span>
                </div>
                <div class="d-flex flex-row justify-content-center align-items-center mt-3">
                    <span class="number">1069 <span class="follow">Followers</span></span>
                </div> #}

                <div class=" d-flex mt-2">
                    <a href="{{ path('app_editProfile') }}" class="btn btn-primary w3-theme-d4 align-self-end mt-auto">Edit</a>
                </div>

                <div class="text mt-3">
                    {% if (is_granted('ROLE_JOBSEEKER')) %}
                        <span class="h2">Skills:{{ app.user.skills}} </span>
                    {% elseif (is_granted('ROLE_RECRUITER')) %}
                        <span class="h2">Skills:{{ app.user.company}} </span>
                    {% endif %}
                    <div>***************************************************************************************************** </div>
                </div>

                <div class="gap-3 mt-3 icons d-flex flex-row justify-content-center align-items-center">
                    <span><i class="fa fa-twitter"></i></span>
                    <span><i class="fa fa-facebook-f"></i></span>
                    <span><i class="fa fa-instagram"></i></span>
                    <span><i class="fa fa-linkedin"></i></span>
                </div>
                <div class=" px-2 rounded mt-4 date ">
                    <span class="join">Joined May,2021</span>
                </div>
            </div>
        </div>
    </div>
{% endblock %}