src/Entity/Job.php
<?php

namespace App\Entity;

use App\Repository\JobRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: JobRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Job
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $position = null;

    #[ORM\Column(length: 1000)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $entreprise = null;

    #[ORM\Column(length: 255)]
    private ?string $location = null;

    #[ORM\Column(length: 255)]
    private ?string $employment_type = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\PrePersist]
    public function setCreatedAt(): void
    {
        if ($this->created_at === null) {
            $this->created_at = new \DateTimeImmutable();
        }
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    #[ORM\ManyToOne(inversedBy: 'jobs')]
    private ?User $recruiter = null;

    /**
     * @var Collection<int, Application>
     */
    #[ORM\OneToMany(targetEntity: Application::class, mappedBy: 'job')]
    private Collection $applications;

    public function __construct()
    {
        $this->applications = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPosition(): ?string
    {
        return $this->position;
    }

    public function setPosition(string $position): static
    {
        $this->position = $position;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getEntreprise(): ?string
    {
        return $this->entreprise;
    }

    public function setEntreprise(string $entreprise): static
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getEmploymentType(): ?string
    {
        return $this->employment_type;
    }

    public function setEmploymentType(string $employment_type): static
    {
        $this->employment_type = $employment_type;

        return $this;
    }

   /* public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }
    */

    public function getRecruiter(): ?User
    {
        return $this->recruiter;
    }

    public function setRecruiter(?User $recruiter): static
    {
        $this->recruiter = $recruiter;

        return $this;
    }

    /**
     * @return Collection<int, Application>
     */
    public function getApplications(): Collection
    {
        return $this->applications;
    }

    public function addApplication(Application $application): static
    {
        if (!$this->applications->contains($application)) {
            $this->applications->add($application);
            $application->setJob($this);
        }

        return $this;
    }

    public function removeApplication(Application $application): static
    {
        if ($this->applications->removeElement($application)) {
            // set the owning side to null (unless already changed)
            if ($application->getJob() === $this) {
                $application->setJob(null);
            }
        }

        return $this;
    }
}

src/Controller/MyJobOffersController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class MyJobOffersController extends AbstractController
{
    #[Route('/myJobOffers', name: 'app_my_job_offers')]
    public function index(): Response
    {

        $user=$this->getUser();

        if (!$user || !$this->isGranted('ROLE_RECRUITER')) {
            throw $this->createAccessDeniedException('You do not have access to this page.');
        }

        $jobs = $user->getJobs();

        return $this->render('my_job_offers/index.html.twig', [
            'jobs' => $jobs,
        ]);
    }
}

templates/my_job_offers/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}My Job Offers{% endblock %}

{% block main %}

    <main class="container d-flex flex-column justify-content-evenly">
        {% for job in jobs %}
            <div class="card w3-theme-l5 " >
                <div class="card-body d-flex flex-column">
                    <div class="card-title">{{ "🚀" ~ job.position }}</div>
                    {#  <span class="text-muted font-italic">{{ jobTimes[job.id] }}</span> #}
                    <div class="tags mb-2 mt-1">
                        <span class="badge bg-secondary">{{ job.employmentType }}</span>
                        {#  <span class="badge bg-primary">{{ job.category }}</span> #}
                    </div>
                    <p class="card-text">{{ job.description | slice(0, 284) ~ '...' }}</p>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item w3-theme-l5">{{ "🧱" ~ job.entreprise }}</li>
                        <li class="list-group-item w3-theme-l5">{{ "📍" ~ job.location }}</li>
                    </ul>
                    <a href="{{ path("app_applications" ,{"job": job.id}) }}" class="btn btn-primary w3-theme-d4 align-self-end mt-auto">See Applications</a>
                </div>
            </div>
        {% endfor %}
    </main>
{% endblock %}